src/login_account/urls.py
from django.urls import path
from django.contrib.auth import views
from . import views

app_name = "login_account"

urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("profile/", views.user_profile, name="profile"),
]

src/school_management/urls.py
from django.urls import path
from .views import SchoolDetailView, SchoolListView, SchoolEditView
from .views import (
    CandidateListView,
    CandidateEditView,
    CandidateDetailView,
    SubstitutionAdminListView,
    SubstitutionDetailView,
    SubstitutionEditView,
    SubstitutionCreateView,
    SubstitutionCreateWithTeacherView,
    SubstitutionCandidatesListView,
    TeacherListView,
    TeacherDetailView,
    TeacherEditView,
    ApplicationCreateView,
    InviteCandidatesView,
    AcceptInvitationView,
    admin_tasks,
    calculate_teacher_availability,
    CommunicationListView,
    ApplicationDetailView,
    ApplicationEditView,
    CandidateCreateView,
    CandidateDeleteView,
    InviteCandidatesView,
    InvitationDetailView,
    AddExecutedByView,
    InvitationEditView,
)

app_name = "school_management"

urlpatterns = [
    path("schools/", SchoolListView.as_view(), name="school_list"),
    path("schools/<int:pk>/", SchoolDetailView.as_view(), name="school_detail"),
    path("schools/<int:pk>/edit/", SchoolEditView.as_view(), name="school_edit"),
    path("candidates/", CandidateListView.as_view(), name="candidate_list"),
    path(
        "candidates/<int:pk>/", CandidateDetailView.as_view(), name="candidate_detail"
    ),
    path(
        "candidates/<int:pk>/edit/", CandidateEditView.as_view(), name="candidate_edit"
    ),
    path("teachers/", TeacherListView.as_view(), name="teacher_list"),
    path("teachers/<int:pk>/", TeacherDetailView.as_view(), name="teacher_detail"),
    path("teachers/<int:pk>/edit/", TeacherEditView.as_view(), name="teacher_edit"),
    path(
        "substitutions_admin/",
        SubstitutionAdminListView.as_view(),
        name="substitution_admin_list",
    ),
    path(
        "substitution/<int:pk>/",
        SubstitutionDetailView.as_view(),
        name="substitution_detail",
    ),
    path(
        "substitution/<int:pk>/edit/",
        SubstitutionEditView.as_view(),
        name="substitution_edit",
    ),
    path(
        "substitution/new/",
        SubstitutionCreateView.as_view(),
        name="substitution_create",
    ),
    path(
        "substitution/new/<int:teacher_id>/",
        SubstitutionCreateWithTeacherView.as_view(),
        name="substitution_create_with_teacher",
    ),
    path(
        "substitutions_candidates/",
        SubstitutionCandidatesListView.as_view(),
        name="substitution_candidates_list",
    ),
    path("admin-tasks/", admin_tasks, name="admin_tasks"),
    path(
        "calculate-availability/",
        calculate_teacher_availability,
        name="calculate_availability",
    ),
    path("find_match/", SubstitutionAdminListView.as_view(), name="find_match"),
    path("login/", SubstitutionEditView.as_view(), name="login"),
    path(
        "application/create/<int:id>/",
        ApplicationCreateView.as_view(),
        name="application_create",
    ),
    path("invitation/<int:id>/", InviteCandidatesView.as_view(), name="invitation_create"),
    path("invitation_accept/<int:id>/", AcceptInvitationView.as_view(), name="invitation_accept"),
    path("communications/", CommunicationListView.as_view(), name="communication_list"),
    path(
        "applications/<int:pk>/",
        ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path(
        "invitations/<int:pk>/",
        InvitationDetailView.as_view(),
        name="invitation_detail",
    ),
    path(
        "applications/edit/<int:pk>/",
        ApplicationEditView.as_view(),
        name="application_edit",
    ),
    path(
        "invitations/edit/<int:pk>/",
        InvitationEditView.as_view(),
        name="invitation_edit",
    ),
    path("candidate/create/", CandidateCreateView.as_view(), name="candidate_create"),
    path(
        "candidate/delete/<int:pk>/",
        CandidateDeleteView.as_view(),
        name="candidate_delete",
    ),
    path(
        "substitution/<int:substitution_id>/add_executed_by/",
        AddExecutedByView.as_view(),
        name="add_executed_by",
    ),

]

src/teach_match/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect


def redirect_to_substitution_candidates(request):
    return redirect("school_management/substitutions_candidates/", permanent=True)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirect_to_substitution_candidates, name="index"),
    path("school_management/", include("school_management.urls")),
    path("login/", include("login_account.urls")),
    path("profile/", views.user_profile, name="user_profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/base.html
{% load custom_filters %}
<!DOCTYPE html>
<html lang="de">

<head>
  {% load static %}
  <title>{% block title %}{% endblock %}</title>
  {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
  <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-custom">
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'school_management:substitution_candidates_list' %}active{% endif %}"
            href="{% url 'school_management:substitution_candidates_list' %}">
            Stellvertretungen
          </a>
        </li>
        {% if request.user|is_in_group:"school-admins" %}
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'school_management:substitution_admin_list' %}active{% endif %}"
            href="{% url 'school_management:substitution_admin_list' %}">
            Stellvertretungen (Verwaltung)
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'school_management:candidate_list' %}active{% endif %}"
            href="{% url 'school_management:candidate_list' %}">
            Stellensuchende
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'school_management:school_list' %}active{% endif %}"
            href="{% url 'school_management:school_list' %}">
            Schul-Standorte</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'school_management:teacher_list' %}active{% endif %}"
            href="{% url 'school_management:teacher_list' %}">Lehrkräfte
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'school_management:application_list' %}active{% endif %}"
            href="{% url 'school_management:communication_list' %}">
            Korrespondenz
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'school_management:admin_tasks' %}active{% endif %}"
            href="{% url 'school_management:admin_tasks' %}">
            Admin
          </a>
        </li>
        {% endif %}
      </ul>

      <!-- Right-aligned items -->
      <ul class="navbar-nav ms-auto">
        {% if not request.user.is_authenticated %}
        <!-- User is not logged in -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login_account:login' %}">Login</a>
        </li>
        {% else %}
        <!-- User is logged in -->
        <li class="nav-item">
          <a class="nav-link"
            href="{% url 'login_account:profile' %}">{{request.user.first_name.0|upper}}{{request.user.last_name.0|upper}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login_account:logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <br>

  {% block content %}{% endblock %}

  <!-- Footer with version number -->
  <footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
      <span class="text-muted">
        &copy; data.bs
        <span style="float:right; font-size: smaller;">v0.0.18 (22.11.2024)</span>
      </span>
    </div>
  </footer>

  {% if messages %}
  <script>
    $(document).ready(function () {
      {% for message in messages %}
      toastr.options = {
        "closeButton": true,
        "progressBar": true,
      }
      toastr.success("{{ message|escapejs }}");
      {% endfor %}
    });
  </script>
  {% endif %}
</body>

</html>

src/templates/user_profile.html
{% extends "base_generic.html" %}

{% block content %}
<h2>User Profile</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save changes</button>
</form>
{% endblock %}