src/school_management/urls.py
from django.urls import path
from .views import SchoolDetailView, SchoolListView, SchoolEditView
from .views import (
    CandidateListView,
    CandidateEditView,
    CandidateDetailView,
    SubstitutionAdminListView,
    SubstitutionDetailView,
    SubstitutionEditView,
    SubstitutionCreateView,
    SubstitutionCreateWithTeacherView,
    SubstitutionCandidatesListView,
    TeacherListView,
    TeacherDetailView,
    TeacherEditView,
    ApplicationCreateView,
    InviteCandidatesView,
    AcceptInvitationView,
    admin_tasks,
    calculate_teacher_availability,
    CommunicationListView,
    ApplicationDetailView,
    ApplicationEditView,
    CandidateCreateView,
    CandidateDeleteView,
    InviteCandidatesView,
    InvitationDetailView,
    AddExecutedByView,
    InvitationEditView,
)

app_name = "school_management"

urlpatterns = [
    path("schools/", SchoolListView.as_view(), name="school_list"),
    path("schools/<int:pk>/", SchoolDetailView.as_view(), name="school_detail"),
    path("schools/<int:pk>/edit/", SchoolEditView.as_view(), name="school_edit"),
    path("candidates/", CandidateListView.as_view(), name="candidate_list"),
    path(
        "candidates/<int:pk>/", CandidateDetailView.as_view(), name="candidate_detail"
    ),
    path(
        "candidates/<int:pk>/edit/", CandidateEditView.as_view(), name="candidate_edit"
    ),
    path("teachers/", TeacherListView.as_view(), name="teacher_list"),
    path("teachers/<int:pk>/", TeacherDetailView.as_view(), name="teacher_detail"),
    path("teachers/<int:pk>/edit/", TeacherEditView.as_view(), name="teacher_edit"),
    path(
        "substitutions_admin/",
        SubstitutionAdminListView.as_view(),
        name="substitution_admin_list",
    ),
    path(
        "substitution/<int:pk>/",
        SubstitutionDetailView.as_view(),
        name="substitution_detail",
    ),
    path(
        "substitution/<int:pk>/edit/",
        SubstitutionEditView.as_view(),
        name="substitution_edit",
    ),
    path(
        "substitution/new/",
        SubstitutionCreateView.as_view(),
        name="substitution_create",
    ),
    path(
        "substitution/new/<int:teacher_id>/",
        SubstitutionCreateWithTeacherView.as_view(),
        name="substitution_create_with_teacher",
    ),
    path(
        "substitutions_candidates/",
        SubstitutionCandidatesListView.as_view(),
        name="substitution_candidates_list",
    ),
    path("admin-tasks/", admin_tasks, name="admin_tasks"),
    path(
        "calculate-availability/",
        calculate_teacher_availability,
        name="calculate_availability",
    ),
    path("find_match/", SubstitutionAdminListView.as_view(), name="find_match"),
    path("login/", SubstitutionEditView.as_view(), name="login"),
    path(
        "application/create/<int:id>/",
        ApplicationCreateView.as_view(),
        name="application_create",
    ),
    path("invitation/<int:id>/", InviteCandidatesView.as_view(), name="invitation_create"),
    path("invitation_accept/<int:id>/", AcceptInvitationView.as_view(), name="invitation_accept"),
    path("communications/", CommunicationListView.as_view(), name="communication_list"),
    path(
        "applications/<int:pk>/",
        ApplicationDetailView.as_view(),
        name="application_detail",
    ),
    path(
        "invitations/<int:pk>/",
        InvitationDetailView.as_view(),
        name="invitation_detail",
    ),
    path(
        "applications/edit/<int:pk>/",
        ApplicationEditView.as_view(),
        name="application_edit",
    ),
    path(
        "invitations/edit/<int:pk>/",
        InvitationEditView.as_view(),
        name="invitation_edit",
    ),
    path("candidate/create/", CandidateCreateView.as_view(), name="candidate_create"),
    path(
        "candidate/delete/<int:pk>/",
        CandidateDeleteView.as_view(),
        name="candidate_delete",
    ),
    path(
        "substitution/<int:substitution_id>/add_executed_by/",
        AddExecutedByView.as_view(),
        name="add_executed_by",
    ),

]

src/teach_match/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect


def redirect_to_substitution_candidates(request):
    return redirect("school_management/substitutions_candidates/", permanent=True)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirect_to_substitution_candidates, name="index"),
    path("school_management/", include("school_management.urls")),
    path("login/", include("login_account.urls")),
    path("profile/", views.user_profile, name="user_profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/school_management/views.py
from multiprocessing import context
from django.utils.timezone import now
from django.http import HttpResponseBadRequest
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.views import View
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView
from django.views.generic.edit import FormView
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from collections import Counter
from django.db.models import Value, CharField
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from .texte import texte
from twilio.rest import Client

from .models import (
    Department,
    CustomUser,
    Teacher,
    Candidate,
    Substitution,
    Subject,
    Timetable,
    Location,
    Level,
    SubstitutionStatus,
    SubstitutionCandidate,
    Invitation,
    Application,
    CommunicationType,
    CommunicationTypeEnum,
    Communication,
    CommunicationResponseType,
    CommunicationResponseTypeEnum,
    SubstitutionStatusEnum,
    SubstitutionExecution,
    SystemVariable
)
from .forms import (
    DepartmentForm,
    CandidateForm,
    SubstitutionCreateForm,
    SubstitutionEditForm,
    TeacherForm,
    InvitationForm,
    ApplicationForm,
    ApplicationRequestForm,
    ConfirmationForm,
    ApplicationResponseForm,
    SubstitutionExecutionForm,
    InvitationEditForm,
    
)
from django.views.generic import ListView  # Import the necessary module
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.db.models.functions import Concat
from django.db.models import F, Value

from .helpers import SubstitutionHelper


class SchoolListView(ListView):
    model = Department
    context_object_name = (
        "schools"  # The name of the variable to be used in the template
    )
    template_name = "school_management/school_list.html"  # Path to the template

    def get_queryset(self):
        queryset = super().get_queryset()  # Get the original queryset
        name_filter = self.request.GET.get("name_filter", "")
        level_filter = self.request.GET.get("level_filter", "")
        location_filter = self.request.GET.get("location_filter", "")

        # Apply filters if present
        if name_filter:
            queryset = queryset.filter(name__icontains=name_filter)
        if level_filter:
            queryset = queryset.filter(level__id=level_filter)
        if location_filter:
            queryset = queryset.filter(location__id=location_filter)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["locations"] = (
            Location.objects.all()
        )  # Pass all locations to the template
        context["levels"] = Level.objects.all()  # Pass all locations to the template
        return context


class SchoolDetailView(DetailView):
    model = Department
    template_name = "school_management/school_detail.html"
    context_object_name = "school"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        school = context["school"]
        # Filter SchoolPerson by school and role ID
        # context["school_teachers"] = Department.school_persons.filter(is_teacher=True)
        context["school_classes"] = Department.class_schools.filter(school=school)
        context["substitutions"] = Department.substitution_schools.filter(school=school)
        lessons = Timetable.objects.filter(school=school)
        teachers = [l.teacher for l in lessons]
        context["teachers"] = list(set(teachers))
        return context


class InvitationEditView(LoginRequiredMixin, UpdateView):
    model = Invitation
    form_class = InvitationEditForm
    template_name = "school_management/invitation_edit.html"
    success_url = reverse_lazy("school_management:communication_list")


class SchoolEditView(LoginRequiredMixin, UpdateView):
    model = Department
    form_class = DepartmentForm
    template_name = "school_management/school_edit.html"
    success_url = reverse_lazy("school_management:school_list")


class CandidateListView(ListView):
    model = Candidate
    context_object_name = (
        "candidates"  
    )
    template_name = "school_management/candidate_list.html"  # Path to the template

    def get_queryset(self):
        queryset = super().get_queryset()  # Get the original queryset
        first_name_filter = self.request.GET.get("first_name_filter", "")
        last_name_filter = self.request.GET.get("last_name_filter", "")
        year_filter = self.request.GET.get("year_filter", "")

        # Apply filters if present
        if first_name_filter:
            queryset = queryset.filter(first_name__icontains=first_name_filter)
        if last_name_filter:
            queryset = queryset.filter(last_name__icontains=last_name_filter)
        if year_filter:
            queryset = queryset.filter(year_of_birth__icontains=year_filter)

        return queryset


class CandidateDetailView(DetailView):
    model = Candidate
    template_name = "school_management/candidate_detail.html"
    context_object_name = "candidate"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        candidate = context["candidate"]
        all_subjects = []
        for substitution_candidate in SubstitutionCandidate.objects.filter(
            candidate=candidate, selected_date__isnull=False
        ):
            h = SubstitutionHelper(substitution_candidate.substitution)
            all_subjects += h.subjects
        context["taught_subjects"] = dict(Counter([x.name for x in all_subjects]))
        context["dateidates"] = dict(Counter([x.name for x in all_subjects]))
        return context


class CandidateEditView(LoginRequiredMixin, UpdateView):
    model = Candidate
    form_class = CandidateForm
    template_name = "school_management/candidate_edit.html"
    success_url = reverse_lazy("school_management:candidate_list")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        action = request.POST.get("action")
        if form.is_valid():
            if action == "save":
                self.object = form.save(commit=False)
                self.object.save()
                return self.form_valid(form)
            elif action == "delete":
                self.object.delete()
                messages.success(request, "Das Profil wurde erfolgreich gelöscht.")
                return redirect(self.success_url)
            else:
                # Handle unknown actions
                return HttpResponseBadRequest(f"{action}:Unbekannte Aktion.")
        else:
            print("Form invalid")
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add the candidate object to the context
        context["candidate"] = self.object
        return context

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)

    def form_invalid(self, form, error=None):
        context = self.get_context_data(form=form)
        if error:
            context["error"] = error
        return self.render_to_response(context)


class TeacherListView(ListView):
    model = Timetable
    template_name = "school_management/teacher_list.html"  # Path to the template
    context_object_name = "teachers"

    def get_queryset(self):
        # Get unique combinations of teacher and school from the Timetable model
        queryset = (
            Timetable.objects.select_related("teacher", "school")
            .values(
                "teacher__id",
                "teacher__first_name",
                "teacher__last_name",
                "teacher__mobile",
                "teacher__email",
                "school__name",
            )
            .distinct()
        )
        name_filter = self.request.GET.get("name_filter", "")
        first_name_filter = self.request.GET.get("first_name_filter", "")
        school_name_filter = self.request.GET.get("school_name_filter", "")

        # Apply filters if present
        if name_filter:
            queryset = queryset.filter(
                teacher__last_name__icontains=name_filter
            )
        if first_name_filter:
            queryset = queryset.filter(
                teacher__first_name__icontains=first_name_filter
            )
        if school_name_filter:
            queryset = queryset.filter(
                school__name__icontains=school_name_filter
            )

        # Order by teacher's last name
        queryset = queryset.order_by("teacher__last_name")

        return queryset


class TeacherDetailView(DetailView):
    model = Teacher
    template_name = "school_management/teacher_detail.html"
    context_object_name = "teacher"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teacher = context["teacher"]
        context["lessons"] = teacher.lessons_template_teachers.all().order_by(
            "day_id", "period_id"
        )
        context["schools"] = list(
            Timetable.objects.filter(teacher=teacher)
            .values_list("school__name", flat=True)
            .distinct()
        )
        context["subjects"] = teacher.get_unique_subjects()
        context["classes"] = teacher.get_unique_classes()
        day_list = teacher.get_unique_days()
        context["days"] = f"{len(day_list)}, ({', '.join(day_list)})"
        return context

src/templates/school_management/candidate_edit.html
{% extends "base.html" %} {% block content %} {% load crispy_forms_tags %} 
{% load static %}
<div class="col-md-6 offset-md-3">
  <div class="form-container">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form|crispy }}
      <div class="form-footer">
        <button type="button" class="btn btn-secondary" onclick="history.back()">Zurück</button>
        <button type="submit" name="action" value="save" class="btn btn-primary">Speichern</button>
        <a href="{% url 'school_management:candidate_create' %}" class="btn btn-success">Neu</a>
        <a href="{% url 'school_management:candidate_delete' candidate.pk %}" class="btn btn-danger"
   onclick="return confirm('Möchten Sie diesen Eintrag wirklich löschen?');">Löschen</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

src/templates/school_management/candidate_list.html
{% extends "base.html" %}
{% block title %}Lehrkraft-Stellvertretung{% endblock title %}
{% load custom_filters %}

{% block content %}
<div class="table-container">
    <h2>Kandidatinnen für Stellvertretungen ({{candidates|length}})</h2>
    <br>
      <form method="get" action="">
        <table id="candidates" class="table table-striped">
            <thead>
                <tr>
                    <th>Nachname</th>
                    <th>Vorname</th>
                    <th>Jahrgang</th>
                    <th>Verfügbarkeit</th>
                    <th>Von</th>
                    <th>Bis</th>
                    <th>Email</th>
                    <th>Telefon</th>
                    <th></th>
                </tr>
                <tr> <!-- Filter inputs row -->
                    <th><input type="text" name="last_name_filter" value="{{ request.GET.last_name_filter }}"></th>
                    <th><input type="text" name="first_name_filter" value="{{ request.GET.first_name_filter }}"></th>
                    <th><input type="text" name="year_filter" value="{{ request.GET.year_filter }}"></th>
                    <th></th>
                    <th><input type="text" name="available_from_filter" value="{{ request.GET.email_filter }}"></th>
                    <th><input type="text" name="avaialable_to_filter" value="{{ request.GET.email_filter }}"></th>
                    <th></th>
                    <th></th>
                    <th>  
                      <button type="submit" class="btn btn-primary">
                        <i class="fas fa-filter"></i>
                      </button>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for candidate in candidates %}
                <tr>
                  <td><a href="{% url 'school_management:candidate_detail' pk=candidate.pk %}">{{ candidate.last_name }}</a></td>
                    <td>{{ candidate.first_name }}</td>
                    <td>{{ candidate.year_of_birth }}</td>
                    <td>
                      <table>
                        <tr>
                            <td>{% if candidate.availability_mo_am %}◉{% else %}○{% endif %}</td>
                            <td>{% if candidate.availability_tu_am %}◉{% else %}○{% endif %}</td>
                            <td>{% if candidate.availability_we_am %}◉{% else %}○{% endif %}</td>
                            <td>{% if candidate.availability_th_am %}◉{% else %}○{% endif %}</td>
                            <td>{% if candidate.availability_fr_am %}◉{% else %}○{% endif %}</td>
                        </tr>
                        <tr>
                          <td>{% if candidate.availability_mo_pm %}◉{% else %}○{% endif %}</td>
                          <td>{% if candidate.availability_tu_pm %}◉{% else %}○{% endif %}</td>
                          <td>{% if candidate.availability_we_pm %}◉{% else %}○{% endif %}</td>
                          <td>{% if candidate.availability_th_pm %}◉{% else %}○{% endif %}</td>
                          <td>{% if candidate.availability_fr_pm %}◉{% else %}○{% endif %}</td>
                      </tr>
                    </table>
                    </td>
                    <td>{{ candidate.available_from_date }}</td>
                    <td>{{ candidate.available_to_date }}</td>
                    <td>{{ candidate.email }}</td>
                    <td>{{ candidate.phone_number }}</td>
                    <td><a href="{% url 'school_management:candidate_edit' pk=candidate.pk %}" title="Profil editieren"><i class="fas fa-edit"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
    </table>    
    
  {% endblock %}

src/templates/school_management/communications_list.html
{% extends "base.html" %}
teach_match/templates/school_management/school_list.html
{% block title %}Bewerbungen{% endblock title %}

{% block content %}
<div class="table-container">
    <h2>Bewerbungen und Einladungen</h2>
    <form method="get" action="">
      <table class="table table-striped">
        <thead>
            <tr>
                <th>Stellvertretung Nr</th>
                <th>Datum Start Stellvertretung</th>
                <th>Typ</th>
                <th>Kandidat*in</th>
                <th>Datum Korrrespondenz</th>
                <th>Antwort Datum</th>
                <th>Antwort</th>
                <th></th>
            </tr>
        </thead>
        <tr> <!-- Filter inputs row -->
          <th><input type="text" name="substitution_filter" value="{{ request.GET.substitution_filter }}"></th>
          <th>
            <table>
              <tr>
                <td>Von:</td><td><input type="date" name="substitution_date_filter_from" value="{{ request.GET.substitution_date_filter_from }}"></td>
              </tr>
              <tr>
                <td>Bis:</td><td><input type="date" name="substitution_date_filter_to" value="{{ request.GET.substitution_date_filter_to }}"></td>
              </tr>
            </table>
          </th>
          <th>
            <select name="communication_type_filter">
              <option value="">Typ</option>
              {% for type in types %}
                  <option value="{{ type.id }}" {% if request.GET.communication_type_filter == type.id|stringformat:"s" %}selected{% endif %}>
                      {{ type.name }}
                  </option>
              {% endfor %}
            </select>
          </th>
          <th><input type="text" name="candidate_filter" value="{{ request.GET.candidate_filter }}"></th>
          <th><input type="text" name="application_date_filter" value="{{ request.GET.application_date_filter }}"></th>
          <th><input type="text" name="application_response_date value="{{ request.GET.application_response_date }}"></th>
          <th>
            <select name="response_filter">
              <option value="">Antwort</option>
              {% for response in responses %}
                  <option value="{{ response.id }}" {% if request.GET.response_filter == response.id|stringformat:"s" %}selected{% endif %}>
                      {{ response.name }}
                  </option>
              {% endfor %}
            </select>
          </th>
          <th>
            <button type="submit" class="btn btn-primary">
              <i class="fas fa-filter"></i>
            </button></th>
      </tr>
        <tbody>
            {% for comm in communications %}
            <tr>
              <td><a href="{% url 'school_management:substitution_detail' pk=comm.substitution.pk %}">{{ comm.substitution.id }}</a></td>
              <td>{{ comm.substitution.start_date }}</td> 
              <td>
                <a href="{% if comm.type.id == 1 %}
                    {% url 'school_management:application_detail' pk=comm.id %}
                  {% else %}
                    {% url 'school_management:invitation_detail' pk=comm.id %}
                  {% endif %}">{{ comm.type }}
                </a>
              </td>
              <td>{{ comm.candidate.fullname }}</td> 
              <td>{{ comm.request_date }}</td> 
              <td>{{ comm.response_date}}</td> 
              <td>{{ comm.response_type.name }}</td> 
              <td><a href="{% if comm.type.id == 1 %}
                  {% url 'school_management:application_edit' pk=comm.pk %}
                {% else %}
                {% url 'school_management:invitation_edit' pk=comm.pk %}
                  {% endif %}" title="Bewerbung beantworten"><i class="fas fa-edit"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </form> 
</div>  
{% endblock %}

""

src/templates/school_management/school_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 
{% block title %}Schul-Standorte{% endblock title %}


{% block content %}
<div class="table-container">
    <h2>Schul-Standorte</h2>
    <form method="get" action="">
      <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Stufe</th>
                <th>Ort</th>
                <th></th>
            </tr>
        </thead>
        <tr> <!-- Filter inputs row -->
          <th><input type="text" name="name_filter" value="{{ request.GET.name_filter }}"></th>
          <th>
            <select name="level_filter">
              <option value="">Alle Stufen</option>
              {% for level in levels %}
                  <option value="{{ level.id }}" {% if request.GET.level_filter == level.id|stringformat:"s" %}selected{% endif %}>
                      {{ level.name }}
                  </option>
              {% endfor %}
            </select>
          </th>
          <th>
            <select name="location_filter">
              <option value="">Alle Orte</option>
              {% for location in locations %}
                  <option value="{{ location.id }}" {% if request.GET.location_filter == location.id|stringformat:"s" %}selected{% endif %}>
                      {{ location.name }}
                  </option>
              {% endfor %}
            </select>
          </th>
          <th>
            <button type="submit" class="btn btn-primary">
              <i class="fas fa-filter"></i>
            </button>
          </th>
      </tr>
        <tbody>
            {% for school in schools %}
            <tr>
                <td><a href="{% url 'school_management:school_detail' pk=school.pk %}">{{ school.name }}</a></td>
                <td>{{ school.level.name }}</td> 
                <td>{{ school.location }}</td> 
                <td><a href="{% url 'school_management:school_edit' pk=school.pk %}" title="Profil editieren"><i class="fas fa-edit"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </form> 
</div>  
{% endblock %}

src/templates/school_management/substitution_admin_list.html
{% extends "base.html" %}
teach_match/templates/school_management/school_list.html
{% block title %}Vikariate{% endblock title %}

{% block content %}
<div class="table-container">
    <h2>Stellvertretungen Admininstration ({{substitutions|length}})</h2>
    <br>
    <a href="{% url 'school_management:substitution_create' %}" class="btn btn-success">Neu</a>
    <br><br>
    <form method="get" action="">
      <table class="table table-striped">
        <thead>
            <tr>
                <th>#Referenz Nummer</th>
                <th>Schule</th>
                <th>Lehrkraft</th>
                <th>Von</th>
                <th>Bis</th>
                <th>Pensum</th>
                <th>Status</th>
                <th></th>
                <th></th>
            </tr>

            <tr> <!-- Filter inputs row -->
              <th><input type="text" name="id_filter" value="{{ request.GET.id_filter }}"></th>
              <th>
                <select name="school_filter">
                  <option value="">---</option>
                  {% for x in schools %}
                      <option value="{{ x.id }}" {% if request.GET.schools_filter == x.id|stringformat:"s" %}selected{% endif %}>
                          {{ x.name }}
                      </option>
                  {% endfor %}
                </select>
              </th>
              <th><input type="text" name="teacher_filter" value="{{ request.GET.teacher_filter }}"></th>
              <th>
                <input type="date" name="date_from_filter" value="{{ request.GET.date_from_filter }}"></th>
              <th>
                <input type="date" name="date_to_filter" value="{{ request.GET.date_to_filter }}">
              </th>
              <th>
                <table>
                  <tr>
                      <td><input type="checkbox" name="mo_am_filter" value="1" {% if request.GET.mo_am_filter %}checked{% endif %}></td>
                      <td><input type="checkbox" name="tu_am_filter" value="1" {% if request.GET.tu_am_filter %}checked{% endif %}></td>
                      <td><input type="checkbox" name="we_am_filter" value="1" {% if request.GET.we_am_filter %}checked{% endif %}></td>
                      <td><input type="checkbox" name="th_am" value="1" {% if request.GET.th_am_filter %}checked{% endif %}></td>
                      <td><input type="checkbox" name="fr_am_filter" value="1" {% if request.GET.fr_am_filter %}checked{% endif %}></td>
                  </tr>
                  <tr>
                    <td><input type="checkbox" name="mo_pm_filter" value="1" {% if request.GET.mo_pm_filter %}checked{% endif %}></td>
                    <td><input type="checkbox" name="tu_pm_filter" value="1" {% if request.GET.tu_pm_filter %}checked{% endif %}></td>
                    <td><input type="checkbox" name="we_pm_filter" value="1" {% if request.GET.we_pm_filter %}checked{% endif %}></td>
                    <td><input type="checkbox" name="th_pm_filter" value="1" {% if request.GET.th_pm_filter %}checked{% endif %}></td>
                    <td><input type="checkbox" name="fr_pm_filter" value="1" {% if request.GET.fr_pm_filter %}checked{% endif %}></td>
                </tr>
              </table>
              </th>
              <th>
              <select name="status_filter">
                <option value="">---</option>
                {% for x in status %}
                    <option value="{{ x.id }}" {% if request.GET.status_filter == x.id|stringformat:"s" %}selected{% endif %}>
                        {{ x.name }}
                    </option>
                {% endfor %}
              </select>
            </th>
              <th><input type="submit" value="Suchen" class="btn btn-primary"></th>
          </tr>
        
          </thead>
        <tbody>
            {% for substitution in substitutions %}
            <tr>
              <td><a href="{% url 'school_management:substitution_detail' pk=substitution.pk %}">{{ substitution.id }}</a></td>
              <td>
                <a href="{% url 'school_management:school_detail' pk=substitution.school.pk %}">{{ substitution.school.name }}</a>
              </td>
              <td><a href="{% url 'school_management:teacher_detail' pk=substitution.teacher.pk %}">{{ substitution.teacher.fullname }}</a></td>
              <td>{{ substitution.start_date }}</td> 
              <td>{{ substitution.end_date }}</td>
              <td>
                <table>
                  <tr>
                      <td>{% if substitution.mo_am %}◉{% else %}○{% endif %}</td>
                      <td>{% if substitution.tu_am %}◉{% else %}○{% endif %}</td>
                      <td>{% if substitution.we_am %}◉{% else %}○{% endif %}</td>
                      <td>{% if substitution.th_am %}◉{% else %}○{% endif %}</td>
                      <td>{% if substitution.fr_am %}◉{% else %}○{% endif %}</td>
                  </tr>
                  <tr>
                    <td>{% if substitution.mo_pm %}◉{% else %}○{% endif %}</td>
                    <td>{% if substitution.tu_pm %}◉{% else %}○{% endif %}</td>
                    <td>{% if substitution.we_pm %}◉{% else %}○{% endif %}</td>
                    <td>{% if substitution.th_pm %}◉{% else %}○{% endif %}</td>
                    <td>{% if substitution.fr_pm %}◉{% else %}○{% endif %}</td>
                </tr>
              </table>
              </td>
              <td>{{ substitution.status.name }}</td> 
              
              <td><a href="{% url 'school_management:substitution_edit' pk=substitution.pk %}" title="Stellvertretung editieren"><i class="fas fa-edit"></i></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </form>
  </div>  
  {% endblock %}